[tool.poetry]
name = "ionic_solana_indexer"
version = "0.1.0"
description = ""
authors = ["pawel <pawel.rainer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
asyncio = "^3.4.3"
aiofiles = "^24.1.0"
aiohttp = "^3.10.5"
orjson = "^3.10.7"
base58 = "^2.1.1"
zstandard = "^0.23.0"
setuptools = "^74.0.0"
aiolimiter = "^1.1.0"
aiolimit = "^0.0.3"
python-dotenv = "^1.0.1"
loguru = "^0.7.2"
urllib3 = "^2.2.3"
fastparquet = "^2024.11.0"
jupyter = "^1.1.1"
notebook = "^7.4.4"
jupyterlab = "^4.3.3"
pandas = "^2.3.1"
dask = "^2025.2.0"
clickhouse-connect = "^0.8.18"
msgspec = "^0.19.0"
tqdm = "^4.67.1"
anchorpy = "^0.21.0"
bip-utils = "^2.9.3"
line-profiler = "^4.2.0"
confluent-kafka = "^2.10.0"
solders = "^0.26.0"
pyarrow = "^21.0.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.6.3"
pytest = "^8.3.2"
pytest-asyncio = "^0.24.0"
pytest-benchmark = "^4.0.0"
jupyter = "^1.1.1"
matplotlib = "^3.9.2"
plotly = "^5.24.0"
ipywidgets = "^8.1.5"

[tool.ruff]
exclude = ["*.ipynb"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
